language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - build-tools-26.0.2
    - android-25
    - android-26
before_script: chmod +x gradlew
script: ./gradlew clean cleanBuildCache assembleDebug
