language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
before_script: chmod +x gradlew
script: ./gradlew clean cleanBuildCache assembleDebug
addons:
  coverity_scan:
    notification_email: dominique.righetto@gmail.com
    build_command: ./gradlew clean cleanBuildCache assembleDebug
